### ISSUE TITLE
使用插件时出现了debug error

### ISSUE THREAD

**Issue by luckycat0426** [JogleLew/coolq-telegram-bot-x#1]
![image](https://user-images.githubusercontent.com/18507944/37254535-23c59584-257a-11e8-8538-74fd1b279879.png)

**Comment by JogleLew** [comment]
由于测试环境采用的是 docker wine 酷 Q，在 Windows 下暂时还没有做充分的测试，所以可能会存在一些问题。最近一段时间可能会尽力修正这些问题和错误，敬请期待。

**Comment by jqqqqqqqqqq** [comment]
帮你翻一下：咕咕咕

**Comment by jqqqqqqqqqq** [comment]
CTBX 还有很长一段路要走，所以请多多反馈！

**Comment by wtdcode** [comment]
尝试一下重构后的CTBX吧！见Release。
