### ISSUE TITLE
Compile Error: "MemoryWriter" isn't a member of the namespace "fmt"

### ISSUE THREAD

**Issue by bjrjk** [JogleLew/coolq-telegram-bot-x#11]
![default](https://user-images.githubusercontent.com/6657270/41930789-aeb63a80-79ae-11e8-9b4a-d259f75c0f90.PNG)
I'm just trying to compile this project and the visual studio raised this error. How to solve this problem?Thanks.

**Comment by bjrjk** [comment]
How to solve this problem:
The problem is caused by the mismatching of "spdlog" and "fmt",the way to solve it is to rollback package "fmt".
Open vcpkg-master\ports\fmt and delete all two files:CONTROL and portfile.cmake .Replace them with repo "Microsoft/vcpkg" 's old "fmt"'s configuration file.(It can be reached here https://github.com/Microsoft/vcpkg/tree/4ce5f064282c3a8d8d710aa82af7aa346b0c6dd5/ports/fmt)
Then remove package fmt and spdlog ,and reinstall them with older version.That's all.
Thanks to @moesoha .

**Comment by moesoha** [comment]
Yeah, I already mentioned this in #9 .

A more pleasant way to rollback is using git: `git checkout <ref_spec> -- ports\<library>` .

`spdlog` was adapted `fmt` v5.0 several weeks ago, but `vcpkg` didn't follow it.

**Comment by wtdcode** [comment]
Thanks.

It seems that the development guide needs updating.
