### ISSUE TITLE
发错误，配置名无效

### ISSUE THREAD

**Issue by 1061302569** [JogleLew/coolq-telegram-bot-x#14]
试了很多个版本都是这个样子，呜呜呜~

**Comment by wtdcode** [comment]
请按照 [提问指引](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/%E6%8F%90%E9%97%AE%E6%8C%87%E5%BC%95) 描述您的问题，谢谢。

**Comment by wtdcode** [comment]
三天没有收到有效反馈，暂时关闭 issue。
