### ISSUE TITLE
无法转发带链接的文字内容

### ISSUE THREAD

**Issue by Ruikoto** [JogleLew/coolq-telegram-bot-x#15]
![image](https://user-images.githubusercontent.com/30781137/51314504-cb4ad980-1a8a-11e9-968f-e0139f745187.png)
例如这种，转发完就只剩文本内容了

**Comment by Ruikoto** [comment]
还有就是各种图片/stickers转发失败的情况

**Comment by wtdcode** [comment]
对于问题1 因为他本身就是链接？
对于问题2 麻烦参照提问指引提供一下必要信息，但是我猜测应该是网络原因导致的，可以检查一下log。

**Comment by Ruikoto** [comment]
> 对于问题1 因为他本身就是链接？

是的，本身就是链接，希望可以让这种的链接分离出来转发到QQ上

**Comment by wtdcode** [comment]
分离出来是什么意思？

**Comment by Ruikoto** [comment]
> 分离出来是什么意思？

抱歉之前没说明白，我指的是在Telegram中的文本可以附带这样[像这样子的链接](example.com)，但是QQ不支持，使用Bot将这类消息转发过去以后就只剩下文本了。如果在转发时，可以让消息附带的链接也转发过去就好了，例如可以在这段文本后面跟一个括号，括号里面放链接。

例如：
转发前（Telegram端） ： [coolq-telegram-bot-x](https://github.com/JogleLew/coolq-telegram-bot-x)
转发后（QQ端）：coolq-telegram-bot-x(https://github.com/JogleLew/coolq-telegram-bot-x)

**Comment by wtdcode** [comment]
哦，我大致理解你的意思了，之后测试的时候会注意一下优化这方面的逻辑。

争取能跟10.3.0一起出来吧。

**Comment by Ruikoto** [comment]
> 哦，我大致理解你的意思了，之后测试的时候会注意一下优化这方面的逻辑。
> 
> 争取能跟10.3.0一起出来吧。

好的 感谢

**Comment by wtdcode** [comment]
Implemented in the version 10.3.1.

**Comment by ghost** [comment]
[初始化失败，原因:"connect: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。"]

请问这个问题怎么解决

**Comment by wtdcode** [comment]
@zaihuame 

请根据 [提问指引](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/%E6%8F%90%E9%97%AE%E6%8C%87%E5%BC%95) 单独打开一个 issue，这个issue跟你的问题无关。
