### ISSUE TITLE
程序访问失败

### ISSUE THREAD

**Issue by jyeric** [JogleLew/coolq-telegram-bot-x#16]
您好请问出现这个问题怎么解决
```
[2019-02-11 21:22:57] [info] [Bot] [Bot开始初始化]
[2019-02-11 21:22:57] [debug] [TGBot] [开始初始化TGBot，根据网络情况需要的时间有较大区别]
[2019-02-11 21:22:57] [debug] [TGBot] [TGBot的Token为:6***********:AA*******************************************]
[2019-02-11 21:23:19] [debug] [TGBot] [初始化失败，原因：connect: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。]
[2019-02-11 21:23:19] [info] [TGBot] [初始化失败，请尝试重新启动Bot。]
```
请问这里的发送API的网址是不是`api.telegram.org`？
api.telegram.org我用firefox测试的
发送
```
https://api.telegram.org/bot66******16:AA*********************************A/sendMessage?chat_id=-1****************&text=%E6%B5%8B%E8%AF%95%E6%B6%88%E6%81%AF
```
效果截图
![temp.JPG](https://i.loli.net/2019/02/11/5c61825706131.jpg)

**Comment by wtdcode** [comment]
用FireFox访问的时候没有走代理吗，可以点开发送的包看看目标地址。

**Comment by jyeric** [comment]
Firefox应该是走的代理，我在[ss](github.com/shadowsocks/shadowsocks)中的pac.txt中已经添加了t.me和telegram.org走代理流量，所以我想询问为什么coolq还是提示无法连接

**Comment by jyeric** [comment]
应该是走的代理，我用ip8.com确认过，我不知道为什么这样coolq还是连接失败

**Comment by wtdcode** [comment]
酷Q本身不支持代理，如果希望酷Q走代理可以用SSTAP等工具。

**Comment by jyeric** [comment]
前面尝试了shadowsocks的pac模式，现在尝试了全局模式，都是提示无法连接

**Comment by jyeric** [comment]
前面百度了一下sstap和ss软件的区别，ss貌似只能代理浏览器中的内容，不能代理其他软件，所以我后面再尝试下sstap，如果成功了我就关闭issue

**Comment by jyeric** [comment]
感谢！

**Comment by 1sm23** [comment]
请问用sstap怎么解决的？

**Comment by wtdcode** [comment]
@GoromitLeo SSTAP类似一个全局代理。另外有问题可以单独开issue。

**Comment by jyeric** [comment]
@GoromitLeo SSTAP是全局，ss是只有浏览器，tcp和udp不转发的（应该是）

**Comment by DeweyLiu** [comment]
请问最终成功了吗 我使用sstap 全局代理  在虚拟机中查看liunx 访问也是走的代理  coolq就是不行

**Comment by wtdcode** [comment]
@DeweyLiu 您好，这里已经提示错误原因是 Not Found 了，应该是 bot 不存在。

**Comment by DeweyLiu** [comment]
> @DeweyLiu 您好，这里已经提示错误原因是 Not Found 了，应该是 bot 不存在。

![image](https://user-images.githubusercontent.com/13083895/61993973-fef46500-b0a6-11e9-8c17-391d7004e293.png)
我token前加了bot  难怪 谢谢  但是目前是这个状况 为什么收不到消息呢

**Comment by wtdcode** [comment]
@DeweyLiu 您好，您的问题比较复杂，请考虑单独开一个issue或者加入支持群提问。

**Comment by DeweyLiu** [comment]
> @DeweyLiu 您好，您的问题比较复杂，请考虑单独开一个issue或者加入支持群提问。

解决了  就是有时候很不稳定 好是coolq崩溃

**Comment by j4i0n4** [comment]
[初始化失败，原因:"handshake: short read"]
这个是什么原因

**Comment by wtdcode** [comment]
墙了。

________________________________
