### ISSUE TITLE
QQ群转发到tg群没问题，TG群消息转发到QQ群需要在消息前面加‘/’才能发出去

### ISSUE THREAD

**Issue by ghost** [JogleLew/coolq-telegram-bot-x#20]
版本 - 10.3.1

**Comment by wtdcode** [comment]
能否按照 [提问指引](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/%E6%8F%90%E9%97%AE%E6%8C%87%E5%BC%95) 提供一些更详细的信息？

**Comment by billchenchina** [comment]
请在 Bot Father 处关闭 Bot 的 Privacy Mode

**Comment by ghost** [comment]
@billchenchina 已经关闭了 bot的Privacy mode 问题依旧

**Comment by wtdcode** [comment]
@sanboukarasu 可能需要重新拉bot到group？ 可以看一眼wiki的faq。

**Comment by ghost** [comment]
可以了，重新拉bot进群就恢复了

**Comment by wtdcode** [comment]
那么本问题关闭。
