### ISSUE TITLE
不好意思，我配置文件这里一直出问题，能麻烦看一下么.

### ISSUE THREAD

**Issue by StrawDC** [JogleLew/coolq-telegram-bot-x#21]
![image](https://user-images.githubusercontent.com/30190369/65957234-e88bd080-e47e-11e9-9634-771d19f9be88.png)

![image](https://user-images.githubusercontent.com/30190369/65957279-00635480-e47f-11e9-8451-c1e3ee766f4d.png)

还有就是给机器挂上了梯子，能够使用吧

**Comment by wtdcode** [comment]
大哥，你先给群名和token打个码，其次你不发完整配置文件我总不能黑了你电脑看吧。。。

然后看一下 [FAQ](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/FAQ) 提供的有在线检测

**Comment by StrawDC** [comment]
> 大哥，你先给群名和token打个码，其次你不发完整配置文件我总不能黑了你电脑看吧。。。
> 
> 然后看一下 [FAQ](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/FAQ) 提供的有在线检测

感谢，检查过后发现是自己压根没改文件名字，现在就剩下用sstap链接了，但ssr能用的sstap一直连不上，正在找问题

**Comment by StrawDC** [comment]
> 大哥，你先给群名和token打个码，其次你不发完整配置文件我总不能黑了你电脑看吧。。。
> 
> 然后看一下 [FAQ](https://github.com/JogleLew/coolq-telegram-bot-x/wiki/FAQ) 提供的有在线检测

还有群和token都是经过删减的😏
