### ISSUE TITLE
Error enabling.

### ISSUE THREAD

**Issue by laosb** [JogleLew/coolq-telegram-bot-x#5]
Config:
```js
{
    "Bot_Token" : "some-token",
    "Bot_QQ" :  99999,
    "Forward_List" :
    [
        {
            "From_Group" : 999999,
            "To_Group" : -99999,
            "Type" : "Q<->T"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/2545261/41013173-5a54810a-6977-11e8-81d2-eb235c7c0cd4.png)

**Comment by billchenchina** [comment]
@laosb Please remove your bot token immediately and revoke your token.

**Comment by laosb** [comment]
@billchenchina Thank you for reminding me of leaking sensitive data. Doing cleaning & revoking.

**Comment by wtdcode** [comment]
Check your permission setting :p.

**Comment by laosb** [comment]
Permission 777 works.
