### ISSUE TITLE
Problem with spdlog and under Windows 7

### ISSUE THREAD

**Issue by moesoha** [JogleLew/coolq-telegram-bot-x#7]
## Problem

  1. When the permission is not enough, `spdlog` will throw an error and cause the plugin exit unexpectedly.
  2. <del>Unknown error when enabling the plugin while using Windows 7 with CoolQ developer mode.</del> Caused by non-ASCII chars.

![snipaste_2018-06-11_16-04-35](https://user-images.githubusercontent.com/5895757/41219543-30c1505c-6d91-11e8-8750-1516fbedfc3a.png)

## Version

CoolQ Pro 5.11.14

The latest ctbx(10.1.0, master branch).

**Comment by moesoha** [comment]
I found the problem 2 is caused by non-ASCII chars in path.

**Comment by wtdcode** [comment]
I will try to catch the exception and edit wiki to emphasize the permission settings next commit.
Thanks.

**Comment by wtdcode** [comment]
fixed.
